{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.name }}-datasources
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Values.victoriaMetrics.name }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.victoriaMetrics.ports.http }}
        isDefault: true
        editable: true
        jsonData:
          timeInterval: {{ .Values.victoriaMetrics.scrapeInterval }}

      - name: VictoriaLogs
        uid: victorialogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://{{ .Values.victoriaLogs.name }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.victoriaLogs.ports.http }}
        editable: true

      - name: VictoriaTraces
        uid: victoriatraces
        type: jaeger
        access: proxy
        url: http://{{ .Values.victoriaTraces.name }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.victoriaTraces.ports.http }}/select/jaeger
        editable: true
        jsonData:
          tracesToLogsV2:
            datasourceUid: victorialogs
            spanStartTimeShift: '-1m'
            spanEndTimeShift: '1m'
            filterByTraceID: true
            filterBySpanID: false
          tracesToMetrics:
            datasourceUid: prometheus
            spanStartTimeShift: '-1m'
            spanEndTimeShift: '1m'
          nodeGraph:
            enabled: true
{{- end }}
