apiVersion: v1
kind: Service
metadata:
  name: {{ include "warp-webapp.fullname" . }}
  labels:
    {{- include "warp-webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.db.port }}
      targetPort: db
      protocol: TCP
      name: db     
  selector:
    {{- include "warp-webapp.selectorLabels" . | nindent 4 }}
