/// <auto-generated/>
// Generated on: 2026-03-26 23:03:01 UTC
using System;
using System.ComponentModel;
using System.Linq;
using Warp.WebApp.Attributes;

namespace Warp.WebApp.Constants.Logging;

public enum LogEvents
{
    // Generic
    [Description("An unexpected error occurred while processing the request. Request ID: '{RequestId}'.")]
    [HttpStatusCode(500)]
    ServerError = 10001,
    [Description("An error occurred while processing the request. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    ServerErrorWithMessage = 10002,
    [Description("The service is temporarily unavailable. Please try again later.")]
    [HttpStatusCode(503)]
    ServiceUnavailable = 10003,


    // Startup
    [Description("Startup error: The Redis host configuration is missing.")]
    [HttpStatusCode(500)]
    RedisHostIsNotSpecified = 11001,
    [Description("Startup error: The Redis port configuration is missing.")]
    [HttpStatusCode(500)]
    RedisPortIsNotSpecified = 11002,
    [Description("Startup error: Failed to connect to Redis. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    RedisConnectionException = 11003,
    [Description("Startup error: Failed to connect to the Vault. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    VaultConnectionException = 11101,
    [Description("Startup error: Failed to cast retrieved secrets to the expected type. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    VaultSecretCastException = 11102,
    [Description("Vault token file '{TokenFile:string}' was not found; set PNKL_VAULT_TOKEN manually.")]
    [HttpStatusCode(500)]
    VaultTokenFileNotFound = 11103,
    [Description("Vault token file '{TokenFile:string}' is empty; set PNKL_VAULT_TOKEN manually.")]
    [HttpStatusCode(500)]
    VaultTokenFileIsEmpty = 11104,
    [Description("Vault token successfully loaded from file '{TokenFile:string}'.")]
    [HttpStatusCode(200)]
    VaultTokenLoadedFromFile = 11105,
    [Description("Local configuration is in use.")]
    [HttpStatusCode(500)]
    LocalConfigurationIsInUse = 11201,
    [Description("End-to-end tests configuration is in use.")]
    [HttpStatusCode(500)]
    EndToEndTestsConfigurationIsInUse = 11202,
    [Description("Startup error: Options validation exception occurred. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    OptionsValidationException = 11301,
    [Description("Startup error: Consul KV key '{StorageName:string}' was not found. Verify the key exists and the service name and environment are configured correctly.")]
    [HttpStatusCode(500)]
    ConsulKvKeyNotFound = 11302,
    [Description("Startup error: Consul KV key '{StorageName:string}' returned null or invalid JSON.")]
    [HttpStatusCode(500)]
    ConsulKvInvalidJson = 11303,
    [Description("Consul KV key '{StorageName:string}' loaded {KeyCount:int} key(s). Values: {ConfigData:string}.")]
    [HttpStatusCode(200)]
    ConsulConfigLoaded = 11304,


    // Infrastructure
    [Description("An internal error occurred. Please try again.")]
    [HttpStatusCode(500)]
    DefaultCacheValueError = 12001,
    [Description("Partial view '{PartialViewName:string}' could not be found. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    PartialViewNotFound = 12101,
    [Description("An error occurred while rendering the partial view '{PartialViewName:string}'. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    PartialViewRenderingError = 12102,
    [Description("Action context not found while trying to build an image URL from a Razor page.")]
    [HttpStatusCode(500)]
    ActionContextNotFound = 12103,
    [Description("Get image controller's method not found.")]
    [HttpStatusCode(500)]
    ImageControllerGetMethodNotFound = 12104,
    [Description("The request could not be validated. Please refresh the page and try again.")]
    [HttpStatusCode(400)]
    CsrfTokenValidationFailure = 12105,
    [Obsolete("This logging event is obsolete and will be removed in a future version.")]
    [Description("An error occurred while uploading the image. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    ImageUploadError = 12201,
    [Obsolete("This logging event is obsolete and will be removed in a future version.")]
    [Description("An error occurred while downloading the image. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    ImageDownloadError = 12202,
    [Obsolete("This logging event is obsolete and will be removed in a future version.")]
    [Description("An error occurred while removing the image. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    ImageRemovalError = 12203,
    [Description("Failed to remove image '{ImageId:Guid}' for entry '{EntryId:Guid}'. Details: '{ErrorMessage:string?}'.")]
    [HttpStatusCode(500)]
    EntryImageCleanupFailure = 12211,
    [Description("Unexpected error while processing entry image cleanup batch. Details: '{ErrorMessage:string?}'.")]
    [HttpStatusCode(500)]
    EntryImageCleanupBatchError = 12212,
    [Description("Giving up on cleaning entry '{EntryId:Guid}' after {FailureCount:int} attempts.")]
    [HttpStatusCode(500)]
    EntryImageCleanupAbandoned = 12213,
    [Description("Orphan image cleanup run started.")]
    [HttpStatusCode(200)]
    OrphanImageCleanupStarted = 12214,
    [Description("Orphan image cleanup run completed. Deleted {DeletedCount:int} images across {ScannedCount:int} scanned objects in {ElapsedSeconds:double} seconds.")]
    [HttpStatusCode(200)]
    OrphanImageCleanupCompleted = 12215,
    [Description("Orphan image cleanup run failed. Details: '{ErrorMessage:string?}'.")]
    [HttpStatusCode(500)]
    OrphanImageCleanupFailed = 12216,
    [Description("An error occurred while uploading the file. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(400)]
    FileUploadException = 12301,
    [Description("File signature verification failed. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(415)]
    UnverifiedFileSignatureError = 12302,
    [Description("File signature verification failed for files with extension '{FileExtension:string}', '{HeaderBytes:string?}'.")]
    [HttpStatusCode(415)]
    FileSignatureVerificationError = 12303,
    [Description("A request with the same idempotency key is already being processed.")]
    [HttpStatusCode(409)]
    RequestIdempotencyKeyViolation = 12401,


    // Domain
    [Description("The entry content cannot be empty.")]
    [HttpStatusCode(400)]
    WarpContentEmpty = 20001,
    [Description("The entry expiration period must be set.")]
    [HttpStatusCode(400)]
    WarpExpirationPeriodEmpty = 20002,
    [Description("An error occurred in the domain layer while removing the image '{ImageId:Guid}'. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(400)]
    ImageRemovalDomainError = 20101,
    [Description("An error occurred while decoding the ID.")]
    [HttpStatusCode(400)]
    IdDecodingError = 20102,
    [Description("You do not have permission to perform this action.")]
    [HttpStatusCode(403)]
    UnauthorizedError = 20103,


    // Domain.Creator
    [Description("The creator ID is missing.")]
    [HttpStatusCode(400)]
    CreatorIdIsNull = 20201,
    [Description("The creator was not found.")]
    [HttpStatusCode(400)]
    CreatorIdIsNotFound = 20202,


    // Domain.Entry
    [Description("An error occurred while attaching the entry to the creator.")]
    [HttpStatusCode(500)]
    CantAttachEntryToCreator = 20301,
    [Description("The entry data is invalid. Please check the provided values.")]
    [HttpStatusCode(400)]
    EntryModelValidationError = 20302,
    [Description("You do not have permission to access this entry.")]
    [HttpStatusCode(403)]
    NoPermissionError = 20303,
    [Description("The entry was not found.")]
    [HttpStatusCode(404)]
    EntryNotFound = 20304,
    [Description("The entry edit mode is already set and cannot be changed.")]
    [HttpStatusCode(400)]
    EntryEditModeMismatch = 20305,
    [Description("The entry cannot be edited after it has been viewed. Try to create a new entry.")]
    [HttpStatusCode(400)]
    EntryCannotBeEditedAfterViewed = 20306,
    [Description("The entry data is invalid. Please check the provided values.")]
    [HttpStatusCode(400)]
    EntryInfoModelValidationError = 20307,
    [Description("Failed to get ciphertext from encryption response. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    VaultCiphertextError = 20308,
    [Description("Failed to get plaintext from decryption response. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    VaultPlaintextError = 20309,
    [Description("The entry edit mode is not set. Please set the edit mode before editing the entry.")]
    [HttpStatusCode(400)]
    EntryEditModeUnset = 20310,
    [Description("The entry text content is too large. Please reduce the size and try again.")]
    [HttpStatusCode(400)]
    EntryPlainTextSizeExceeded = 20311,
    [Description("The entry content is too large. Please reduce the size and try again.")]
    [HttpStatusCode(400)]
    EntryHtmlSizeExceeded = 20312,
    [Description("Content delta is required for advanced mode entries.")]
    [HttpStatusCode(400)]
    EntryContentDeltaRequired = 20313,
    [Description("The entry content delta is not valid JSON.")]
    [HttpStatusCode(400)]
    EntryContentDeltaInvalidJson = 20314,
    [Description("The entry content delta is too large. Please reduce the size and try again.")]
    [HttpStatusCode(400)]
    EntryContentDeltaSizeExceeded = 20315,


    // Domain.Image
    [Description("The file extension '{FileExtension:string}' is not supported. Please use one of the following extensions: {SupportedFileExtensions:string}.")]
    [HttpStatusCode(415)]
    UnsupportedFileExtension = 20401,
    [Description("The image '{UntrustedImageName:string}' you are trying to upload already exists.")]
    [HttpStatusCode(400)]
    ImageAlreadyExists = 20402,
    [Description("Image '{ImageId:Guid}' was flagged as malicious by GuardDuty and has been excluded from entry '{EntryId:Guid}'.")]
    [HttpStatusCode(400)]
    MaliciousImageDetected = 20403,
    [Description("All uploaded images were flagged as malicious. The entry cannot be created.")]
    [HttpStatusCode(400)]
    AllImagesMalicious = 20404,
    [Description("Malware scan for image '{ImageId:Guid}' did not complete within the timeout period. The image will be treated as clean.")]
    [HttpStatusCode(400)]
    MalwareScanTimeout = 20405,
    [Description("Malware scan for image '{ImageId:Guid}' failed. Details: '{ErrorMessage:string}'.")]
    [HttpStatusCode(500)]
    MalwareScanError = 20406,
    [Description("One or more images failed a malware scan. The entry was not created.")]
    [HttpStatusCode(500)]
    MaliciousImageRemovalFailed = 20407,


    // Domain.File
    [Description("An error occurred while listing objects.")]
    [HttpStatusCode(500)]
    S3ListObjectsError = 20501,
    [Description("An error occurred while deleting an object.")]
    [HttpStatusCode(500)]
    S3DeleteObjectError = 20502,
    [Description("An error occurred while uploading an object.")]
    [HttpStatusCode(500)]
    S3UploadObjectError = 20503,
    [Description("An error occurred while getting an object.")]
    [HttpStatusCode(500)]
    S3GetObjectError = 20504,
    [Description("The file name is missing.")]
    [HttpStatusCode(400)]
    FileNameIsMissing = 20505,
    [Description("The file is empty. Please provide a non-empty file.")]
    [HttpStatusCode(400)]
    FileIsEmpty = 20506,
    [Description("The file is too large. Please upload a smaller file.")]
    [HttpStatusCode(400)]
    FileSizeExceeded = 20507,
    [Description("This file type is not permitted.")]
    [HttpStatusCode(400)]
    FileTypeNotPermitted = 20508,
    [Description("The request format is invalid.")]
    [HttpStatusCode(400)]
    MultipartReaderError = 20509,
    [Description("The request content type is invalid.")]
    [HttpStatusCode(400)]
    MultipartContentTypeBoundaryError = 20510,
    [Description("The request boundary limit has been exceeded.")]
    [HttpStatusCode(400)]
    MultipartBoundaryLengthLimitExceeded = 20511,
}
