/// <auto-generated/>
// Generated on: 2025-11-09 22:19:31 UTC
using System;
using Microsoft.Extensions.Logging;
using Warp.WebApp.Constants.Logging;

#nullable enable
#pragma warning disable CS0618 // Type or member is obsolete

namespace Warp.WebApp.Telemetry.Logging;

internal static partial class LogMessages
{
    // Generic
    [LoggerMessage((int)LogEvents.ServerError, LogLevel.Error, "An unexpected error occurred while processing the request. Request ID: '{RequestId}'.")]
    public static partial void LogServerError(this ILogger logger, string? requestId);

    [LoggerMessage((int)LogEvents.ServerErrorWithMessage, LogLevel.Error, "An error occurred while processing the request. Request ID: {RequestId}. Details: '{ErrorMessage:string}'.")]
    public static partial void LogServerErrorWithMessage(this ILogger logger, string? requestId, string errorMessage);

    [LoggerMessage((int)LogEvents.ServiceUnavailable, LogLevel.Error, "Service unavailable (503). Request ID: {RequestId}. Details: '{ErrorMessage:string}'.")]
    public static partial void LogServiceUnavailable(this ILogger logger, string? requestId, string errorMessage);


    // Startup
    [LoggerMessage((int)LogEvents.RedisHostIsNotSpecified, LogLevel.Critical, "Startup error: The Redis host configuration is missing.")]
    public static partial void LogRedisHostIsNotSpecified(this ILogger logger);

    [LoggerMessage((int)LogEvents.RedisPortIsNotSpecified, LogLevel.Critical, "Startup error: The Redis port configuration is missing.")]
    public static partial void LogRedisPortIsNotSpecified(this ILogger logger);

    [LoggerMessage((int)LogEvents.RedisConnectionException, LogLevel.Critical, "Startup error: Failed to connect to Redis. Details: '{ErrorMessage:string}'.")]
    public static partial void LogRedisConnectionException(this ILogger logger, string errorMessage);

    [LoggerMessage((int)LogEvents.VaultConnectionException, LogLevel.Critical, "Startup error: Failed to connect to the Vault. Details: '{ErrorMessage:string}'.")]
    public static partial void LogVaultConnectionException(this ILogger logger, string errorMessage);

    [LoggerMessage((int)LogEvents.VaultSecretCastException, LogLevel.Critical, "Startup error: Failed to cast retrieved secrets to the expected type. Details: '{ErrorMessage:string}'.")]
    public static partial void LogVaultSecretCastException(this ILogger logger, string errorMessage);

    [LoggerMessage((int)LogEvents.LocalConfigurationIsInUse, LogLevel.Information, "Local configuration is in use.")]
    public static partial void LogLocalConfigurationIsInUse(this ILogger logger);

    [LoggerMessage((int)LogEvents.OptionsValidationException, LogLevel.Error, "Startup error: Options validation exception occurred. Details: '{ErrorMessage:string}'.")]
    public static partial void LogOptionsValidationException(this ILogger logger, string errorMessage);


    // Infrastructure
    [LoggerMessage((int)LogEvents.DefaultCacheValueError, LogLevel.Warning, "Unable to store a default value {CacheValue}.")]
    public static partial void LogDefaultCacheValueError(this ILogger logger, string? cacheValue);

    [LoggerMessage((int)LogEvents.PartialViewNotFound, LogLevel.Critical, "Partial view '{PartialViewName:string}' could not be found. Details: '{ErrorMessage:string}'.")]
    public static partial void LogPartialViewNotFound(this ILogger logger, string partialViewName, string errorMessage);

    [LoggerMessage((int)LogEvents.PartialViewRenderingError, LogLevel.Critical, "An error occurred while rendering the partial view '{PartialViewName:string}'. Details: '{ErrorMessage:string}'.")]
    public static partial void LogPartialViewRenderingError(this ILogger logger, string partialViewName, string errorMessage);

    [LoggerMessage((int)LogEvents.ActionContextNotFound, LogLevel.Critical, "Action context not found while trying to build an image URL from a Razor page.")]
    public static partial void LogActionContextNotFound(this ILogger logger);

    [LoggerMessage((int)LogEvents.ImageControllerGetMethodNotFound, LogLevel.Critical, "Get image controller's method not found.")]
    public static partial void LogImageControllerGetMethodNotFound(this ILogger logger);

    [Obsolete("This log message is obsolete. Do not use it.")]
    [LoggerMessage((int)LogEvents.ImageUploadError, LogLevel.Error, "An error occurred while uploading the image. Details: '{ErrorMessage:string}'.")]
    public static partial void LogImageUploadError(this ILogger logger, string errorMessage);

    [Obsolete("This log message is obsolete. Do not use it.")]
    [LoggerMessage((int)LogEvents.ImageDownloadError, LogLevel.Error, "An error occurred while downloading the image. Details: '{ErrorMessage:string}'.")]
    public static partial void LogImageDownloadError(this ILogger logger, string errorMessage);

    [Obsolete("This log message is obsolete. Do not use it.")]
    [LoggerMessage((int)LogEvents.ImageRemovalError, LogLevel.Error, "An error occurred while removing the image. Details: '{ErrorMessage:string}'.")]
    public static partial void LogImageRemovalError(this ILogger logger, string errorMessage);

    [LoggerMessage((int)LogEvents.EntryImageCleanupFailure, LogLevel.Warning, "Failed to remove image '{ImageId:Guid}' for entry '{EntryId:Guid}'. Details: '{ErrorMessage:string?}'.")]
    public static partial void LogEntryImageCleanupFailure(this ILogger logger, Guid imageId, Guid entryId, string? errorMessage);

    [LoggerMessage((int)LogEvents.EntryImageCleanupBatchError, LogLevel.Error, "Unexpected error while processing entry image cleanup batch. Details: '{ErrorMessage:string?}'.")]
    public static partial void LogEntryImageCleanupBatchError(this ILogger logger, Exception exception, string? errorMessage);

    [LoggerMessage((int)LogEvents.EntryImageCleanupAbandoned, LogLevel.Error, "Giving up on cleaning entry '{EntryId:Guid}' after {FailureCount:int} attempts.")]
    public static partial void LogEntryImageCleanupAbandoned(this ILogger logger, Guid entryId, int failureCount);

    [LoggerMessage((int)LogEvents.OrphanImageCleanupStarted, LogLevel.Information, "Orphan image cleanup run started.")]
    public static partial void LogOrphanImageCleanupStarted(this ILogger logger);

    [LoggerMessage((int)LogEvents.OrphanImageCleanupCompleted, LogLevel.Information, "Orphan image cleanup run completed. Deleted {DeletedCount:int} images across {ScannedCount:int} scanned objects in {ElapsedSeconds:double} seconds.")]
    public static partial void LogOrphanImageCleanupCompleted(this ILogger logger, int deletedCount, int scannedCount, double elapsedSeconds);

    [LoggerMessage((int)LogEvents.OrphanImageCleanupFailed, LogLevel.Error, "Orphan image cleanup run failed. Details: '{ErrorMessage:string?}'.")]
    public static partial void LogOrphanImageCleanupFailed(this ILogger logger, Exception exception, string? errorMessage);

    [LoggerMessage((int)LogEvents.FileUploadException, LogLevel.Error, "An error occurred while uploading the file. Details: '{ErrorMessage:string}'.")]
    public static partial void LogFileUploadException(this ILogger logger, string errorMessage);

    [LoggerMessage((int)LogEvents.UnverifiedFileSignatureError, LogLevel.Error, "File signature verification failed. Details: '{ErrorMessage:string}'.")]
    public static partial void LogUnverifiedFileSignatureError(this ILogger logger, string errorMessage);

    [LoggerMessage((int)LogEvents.FileSignatureVerificationError, LogLevel.Warning, "File signature verification failed for files with extension '{FileExtension:string}', '{HeaderBytes:string?}'.")]
    public static partial void LogFileSignatureVerificationError(this ILogger logger, string fileExtension, string? headerBytes);


    // Domain
    [LoggerMessage((int)LogEvents.ImageRemovalDomainError, LogLevel.Error, "An error occurred in the domain layer while removing the image '{ImageId:Guid}'. Details: '{ErrorMessage:string}'.")]
    public static partial void LogImageRemovalDomainError(this ILogger logger, Guid imageId, string errorMessage);


    // Domain.Creator
    [LoggerMessage((int)LogEvents.CreatorIdIsNull, LogLevel.Warning, "The creator ID is not provided.")]
    public static partial void LogCreatorIdIsNull(this ILogger logger);


    // Domain.Entry
    [LoggerMessage((int)LogEvents.CantAttachEntryToCreator, LogLevel.Error, "Can't attach the entry '{EntryId:Guid}' to the creator '{CreatorId:Guid}' due to an internal server error.")]
    public static partial void LogCantAttachEntryToCreator(this ILogger logger, Guid entryId, Guid creatorId);

    [LoggerMessage((int)LogEvents.VaultCiphertextError, LogLevel.Critical, "Failed to get ciphertext from encryption response. Details: '{ErrorMessage:string}'.")]
    public static partial void LogVaultCiphertextError(this ILogger logger, string errorMessage);

    [LoggerMessage((int)LogEvents.VaultPlaintextError, LogLevel.Critical, "Failed to get plaintext from decryption response. Details: '{ErrorMessage:string}'.")]
    public static partial void LogVaultPlaintextError(this ILogger logger, string errorMessage);


    // Domain.File
    [LoggerMessage((int)LogEvents.S3ListObjectsError, LogLevel.Error, "An error occurred while listing objects in S3. Details: '{ErrorMessage:string}'.")]
    public static partial void LogS3ListObjectsError(this ILogger logger, string errorMessage);

    [LoggerMessage((int)LogEvents.S3DeleteObjectError, LogLevel.Error, "An error occurred while deleting an object from S3. Details: '{ErrorMessage:string}'.")]
    public static partial void LogS3DeleteObjectError(this ILogger logger, string errorMessage);

    [LoggerMessage((int)LogEvents.S3UploadObjectError, LogLevel.Error, "An error occurred while uploading an object to S3. Details: '{ErrorMessage:string}'.")]
    public static partial void LogS3UploadObjectError(this ILogger logger, string errorMessage);

    [LoggerMessage((int)LogEvents.S3GetObjectError, LogLevel.Error, "An error occurred while getting an object from S3. Details: '{ErrorMessage:string}'.")]
    public static partial void LogS3GetObjectError(this ILogger logger, string errorMessage);
}

#pragma warning restore CS0618 // Type or member is obsolete
#nullable disable
