using System.Text;
using Warp.CodeGen.Models;
using Warp.CodeGen.Utilities;

namespace Warp.CodeGen.Generators;

/// <summary>
/// Generates the DomainErrors.cs file containing static methods for creating DomainError instances
/// </summary>
public partial class DomainErrorGenerator : BaseGenerator
{
    public static void Generate(LoggingConfig loggingConfig, string outputFilePath)
    {
        Console.WriteLine($"Generating domain errors to {outputFilePath}");
        
        var sb = new StringBuilder();
        sb.AppendLine("/// <auto-generated/>");
        sb.AppendLine("// Generated on: " + DateTimeOffset.UtcNow.ToString("yyyy-MM-dd HH:mm:ss UTC"));
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Warp.WebApp.Constants.Logging;");
        sb.AppendLine("using Warp.WebApp.Constants;");
        sb.AppendLine();
        sb.AppendLine("#pragma warning disable IDE0130 // Namespace does not match folder structure");
        sb.AppendLine("namespace Warp.WebApp.Models.Errors;");
        sb.AppendLine("#pragma warning restore IDE0130 // Namespace does not match folder structure");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides static methods to create domain error instances");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class DomainErrors");
        sb.AppendLine("{");
        
        var eventsWithDomainError = loggingConfig.LoggingCategories
            .SelectMany(c => c.Events.Select(e => (Category: c, Event: e)))
            .Where(x => x.Event.DomainErrorDescription != null)
            .ToList();

        var isFirst = true;
        foreach (var (_, logEvent) in eventsWithDomainError)
        {
            if (!isFirst)
                sb.AppendLine();

            isFirst = false;

            if (logEvent.Obsolete)
                sb.AppendLine($"    [Obsolete(\"This error is obsolete. Do not use.\")]");

            var description = logEvent.DomainErrorDescription!["en"];
            var methodParameters = ExtractParameters(description);
            var methodArguments = GetMethodArguments(description);
            var indexedDescription = ConvertToIndexedFormat(description);
            var hasParameters = !string.IsNullOrEmpty(methodArguments);

            sb.AppendLine($"    public static DomainError {logEvent.Name}({methodParameters})");

            if (hasParameters)
            {
                sb.AppendLine($"        => new DomainError(LogEvents.{logEvent.Name}, string.Format(\"{indexedDescription}\", {methodArguments}))");
                sb.AppendLine($"            .WithExtension(ErrorExtensionKeys.ErrorParams, new object?[] {{ {methodArguments} }});");
            }
            else
            {
                sb.AppendLine($"        => new(LogEvents.{logEvent.Name});");
            }
        }
        
        sb.AppendLine("}");
        
        FileUtilities.WriteToFile(outputFilePath, sb.ToString());
    }
}