using System.Text;
using Warp.CodeGen.Models;
using Warp.CodeGen.Utilities;

namespace Warp.CodeGen.Generators;

/// <summary>
/// Generates per-locale TypeScript files mapping event IDs to localized domain error messages.
/// </summary>
public partial class I18nErrorGenerator : BaseGenerator
{
    public static void Generate(LoggingConfig loggingConfig, string outputDirectory)
    {
        Console.WriteLine($"Generating i18n domain error files to {outputDirectory}");

        var locales = DiscoverLocales(loggingConfig);
        foreach (var locale in locales)
            GenerateLocaleFile(loggingConfig, outputDirectory, locale);
    }


    private static void GenerateLocaleFile(LoggingConfig loggingConfig, string outputDirectory, string locale)
    {
        var events = loggingConfig.LoggingCategories
            .SelectMany(c => c.Events)
            .Where(e => e.DomainErrorDescription != null)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("/// <auto-generated/>");
        sb.AppendLine("// Generated on: " + DateTimeOffset.UtcNow.ToString("yyyy-MM-dd HH:mm:ss UTC"));
        sb.AppendLine("// Do not edit this file directly. Edit log-events.json and run Warp.CodeGen instead.");
        sb.AppendLine();
        sb.AppendLine("const domainErrors: Record<number, string> = {");

        foreach (var logEvent in events)
        {
            var message = logEvent.DomainErrorDescription!.GetValueOrDefault(locale)
                ?? logEvent.DomainErrorDescription!.GetValueOrDefault("en");

            if (message is null)
                continue;

            var template = ConvertToIndexedFormat(message);
            sb.AppendLine($"    {logEvent.Id}: '{EscapeForTypeScript(template)}',");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("export default domainErrors");

        var outputPath = Path.Combine(outputDirectory, $"domain-errors.{locale}.ts");
        FileUtilities.WriteToFile(outputPath, sb.ToString());
    }


    private static IReadOnlyList<string> DiscoverLocales(LoggingConfig loggingConfig)
    {
        var locales = new HashSet<string>();
        foreach (var category in loggingConfig.LoggingCategories)
        {
            foreach (var logEvent in category.Events)
            {
                if (logEvent.DomainErrorDescription is null)
                    continue;

                foreach (var locale in logEvent.DomainErrorDescription.Keys)
                    locales.Add(locale);
            }
        }

        return [.. locales.OrderBy(l => l)];
    }


    private static string EscapeForTypeScript(string value)
        => value.Replace("\\", "\\\\").Replace("'", "\\'");
}
