/// <auto-generated/>
// Generated on: 2026-03-20 00:18:29 UTC
#nullable enable
using Warp.WebApp.Constants.Logging;
using Warp.WebApp.Constants;

#pragma warning disable IDE0130 // Namespace does not match folder structure
namespace Warp.WebApp.Models.Errors;
#pragma warning restore IDE0130 // Namespace does not match folder structure

/// <summary>
/// Provides static methods to create domain error instances
/// </summary>
public static class DomainErrors
{
    public static DomainError ServerErrorWithMessage(string errorMessage)
        => new DomainError(LogEvents.ServerErrorWithMessage, string.Format("An error occurred while processing the request. Details: '{0}'.", errorMessage))
            .WithExtension(ErrorExtensionKeys.ErrorParams, new object?[] { errorMessage });

    public static DomainError ServiceUnavailable()
        => new(LogEvents.ServiceUnavailable);

    public static DomainError DefaultCacheValueError()
        => new(LogEvents.DefaultCacheValueError);

    public static DomainError RequestIdempotencyKeyViolation()
        => new(LogEvents.RequestIdempotencyKeyViolation);

    public static DomainError WarpContentEmpty()
        => new(LogEvents.WarpContentEmpty);

    public static DomainError WarpExpirationPeriodEmpty()
        => new(LogEvents.WarpExpirationPeriodEmpty);

    public static DomainError IdDecodingError()
        => new(LogEvents.IdDecodingError);

    public static DomainError UnauthorizedError()
        => new(LogEvents.UnauthorizedError);

    public static DomainError CreatorIdIsNull()
        => new(LogEvents.CreatorIdIsNull);

    public static DomainError CreatorIdIsNotFound()
        => new(LogEvents.CreatorIdIsNotFound);

    public static DomainError CantAttachEntryToCreator()
        => new(LogEvents.CantAttachEntryToCreator);

    public static DomainError EntryModelValidationError()
        => new(LogEvents.EntryModelValidationError);

    public static DomainError NoPermissionError()
        => new(LogEvents.NoPermissionError);

    public static DomainError EntryNotFound()
        => new(LogEvents.EntryNotFound);

    public static DomainError EntryEditModeMismatch()
        => new(LogEvents.EntryEditModeMismatch);

    public static DomainError EntryCannotBeEditedAfterViewed()
        => new(LogEvents.EntryCannotBeEditedAfterViewed);

    public static DomainError EntryInfoModelValidationError()
        => new(LogEvents.EntryInfoModelValidationError);

    public static DomainError EntryEditModeUnset()
        => new(LogEvents.EntryEditModeUnset);

    public static DomainError EntryPlainTextSizeExceeded()
        => new(LogEvents.EntryPlainTextSizeExceeded);

    public static DomainError EntryHtmlSizeExceeded()
        => new(LogEvents.EntryHtmlSizeExceeded);

    public static DomainError EntryContentDeltaRequired()
        => new(LogEvents.EntryContentDeltaRequired);

    public static DomainError EntryContentDeltaInvalidJson()
        => new(LogEvents.EntryContentDeltaInvalidJson);

    public static DomainError EntryContentDeltaSizeExceeded()
        => new(LogEvents.EntryContentDeltaSizeExceeded);

    public static DomainError UnsupportedFileExtension(string fileExtension, string supportedFileExtensions)
        => new DomainError(LogEvents.UnsupportedFileExtension, string.Format("The file extension '{0}' is not supported. Please use one of the following extensions: {1}.", fileExtension, supportedFileExtensions))
            .WithExtension(ErrorExtensionKeys.ErrorParams, new object?[] { fileExtension, supportedFileExtensions });

    public static DomainError ImageAlreadyExists(string untrustedImageName)
        => new DomainError(LogEvents.ImageAlreadyExists, string.Format("The image '{0}' you are trying to upload already exists.", untrustedImageName))
            .WithExtension(ErrorExtensionKeys.ErrorParams, new object?[] { untrustedImageName });

    public static DomainError AllImagesMalicious()
        => new(LogEvents.AllImagesMalicious);

    public static DomainError MaliciousImageRemovalFailed()
        => new(LogEvents.MaliciousImageRemovalFailed);

    public static DomainError S3ListObjectsError()
        => new(LogEvents.S3ListObjectsError);

    public static DomainError S3DeleteObjectError()
        => new(LogEvents.S3DeleteObjectError);

    public static DomainError S3UploadObjectError()
        => new(LogEvents.S3UploadObjectError);

    public static DomainError S3GetObjectError()
        => new(LogEvents.S3GetObjectError);

    public static DomainError FileNameIsMissing()
        => new(LogEvents.FileNameIsMissing);

    public static DomainError FileIsEmpty()
        => new(LogEvents.FileIsEmpty);

    public static DomainError FileSizeExceeded()
        => new(LogEvents.FileSizeExceeded);

    public static DomainError FileTypeNotPermitted()
        => new(LogEvents.FileTypeNotPermitted);

    public static DomainError MultipartReaderError()
        => new(LogEvents.MultipartReaderError);

    public static DomainError MultipartContentTypeBoundaryError()
        => new(LogEvents.MultipartContentTypeBoundaryError);

    public static DomainError MultipartBoundaryLengthLimitExceeded()
        => new(LogEvents.MultipartBoundaryLengthLimitExceeded);
}
