import DOMPurify from 'dompurify'


const ALLOWED_TAGS = [
    'b',
    'i',
    'u',
    's',
    'em',
    'strong',
    'h1',
    'h2',
    'h3',
    'p',
    'br',
    'ol',
    'ul',
    'li',
    'a',
    'blockquote',
    'pre',
    'code',
    'span',
]


const ALLOWED_ATTR = ['href', 'target', 'rel']


const ALLOWED_URI_REGEXP = /^(?:https?:|mailto:)/i


/**
 * Sanitizes HTML content using DOMPurify with a strict allow-list matching Tiptap's output.
 * Only allows tags and attributes generated by the RichTextEditor component.
 * Strips scripts, event handlers, and dangerous attributes.
 */
export function sanitize(html: string): string {
    if (!html || html.trim() === '')
        return ''

    const clean = DOMPurify.sanitize(html, {
        ALLOWED_TAGS,
        ALLOWED_ATTR,
        ALLOWED_URI_REGEXP,
        ALLOW_DATA_ATTR: false,
        ALLOW_UNKNOWN_PROTOCOLS: false,
        SAFE_FOR_TEMPLATES: true,
        WHOLE_DOCUMENT: false,
        RETURN_DOM: false,
        RETURN_DOM_FRAGMENT: false,
        FORCE_BODY: false,
    })

    return clean
}


/**
 * Strips all HTML tags from the input and returns plain text.
 * Useful for generating plain-text previews or validating non-empty content.
 */
export function stripHtml(html: string): string {
    if (!html || html.trim() === '')
        return ''

    const clean = DOMPurify.sanitize(html, {
        ALLOWED_TAGS: [],
        KEEP_CONTENT: true,
    })

    return clean.trim()
}


/**
 * Checks if the HTML content contains meaningful text after stripping tags.
 * Returns false for empty strings or HTML containing only whitespace/empty tags.
 */
export function hasTextContent(html: string): boolean {
    const plainText = stripHtml(html)
    return plainText.length > 0
}
