// Problem Details (RFC 7807-like) shape used by the frontend.
// Required fields: type, title, status, detail, traceId (note: server may send 'trace-id').
// Optional fields may include eventId, sentryId, stackTrace, errors (validation), plus any additional members.

/** Represents problem details as per RFC 7807-like structure. */
export interface ProblemDetails {
    /** A URI reference that identifies the problem type. */
    type: string
    /** A short, human-readable summary of the problem type. */
    title: string
    /** The HTTP status code generated by the origin server. */
    status: number
    /** A human-readable explanation specific to this occurrence of the problem. */
    detail: string
    /** Correlation / trace identifier (server original key 'trace-id'). */
    traceId: string

    /** Optional server event identifier (server key 'event-id'). */
    eventId?: number
    /** Optional Sentry identifier for error tracking (server key 'sentry-id'). */
    sentryId?: string
    /** Server stack trace (server key 'stack-trace'). */
    stackTrace?: string
    /** Validation / domain errors bag. Each property -> list of messages. */
    errors?: Record<string, string[]>

    /** Additional arbitrary extension members. */
    [extension: string]: unknown
}


/** Alias for ProblemDetails when partials are allowed. */
export type ProblemDetailsLike = ProblemDetails // alias for clarity when partials not allowed yet
